### ISSUE TITLE
Bug Report: Repair docs build

### ISSUE THREAD

**Issue by Priusds** [Priusds/ParGeo#79]
**Describe the bug**
The docs are not build correctly, all docstrings are missing.

**To Reproduce**
Please provide a minimal code snippet where the bug appears.

**Expected behavior**

**Screenshots**

**Working environment (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu] and its version
 - Python version
 - Gmsh version (if Gmsh is needed)

**Additional context**

**Comment by Priusds** [comment]
<img width="630" alt="Screenshot 2024-02-18 at 22 30 35" src="https://github.com/Priusds/ParGeo/assets/30956139/52f6faac-9b18-4bee-a603-665487fdb5ab">

**Comment by Priusds** [comment]
```yml
# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies
      - poetry install --with docs
```

could be the solution.
